#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Emit the DUT instance line for testbench.spice from the extracted netlist.
#
# magic's "flatten" discards the port index ordering, so the .subckt pin list
# comes out in an order that depends on the tool version and shifts whenever the
# layout is edited. A hard-coded positional pin list in the testbench then
# silently connects the supplies to the wrong pins and the run yields nonsense
# rather than an error, so build the instance line from the netlist instead.
#
# Every port maps to a node of the same name, except the unused inputs, which
# are tied to VGND.

import re
import sys

TIE_LOW = ("ui_in", "uio_in")


def ports(netlist: str) -> list[str]:
    m = re.search(
        r"^\.subckt\s+tt_um_oscillating_bones\s+(.*?)(?=^[^+])", netlist, re.S | re.M
    )
    if not m:
        raise SystemExit("no tt_um_oscillating_bones .subckt found in the netlist")
    return m.group(1).replace("\n+", " ").split()


def main(netlist_path: str, output_path: str) -> None:
    with open(netlist_path) as f:
        pins = ports(f.read())
    nodes = ["VGND" if p.startswith(TIE_LOW) else p for p in pins]

    lines, current = [], "x1"
    for node in nodes + ["tt_um_oscillating_bones"]:
        if len(current) + len(node) + 1 > 88:
            lines.append(current)
            current = "+"
        current += " " + node
    lines.append(current)

    with open(output_path, "w") as f:
        f.write("* Generated by gen_dut_inst.py - do not edit\n")
        f.write("\n".join(lines) + "\n")
    print(f"{output_path}: {len(pins)} ports")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
